source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'TFBubbleItUp_Example' do
  pod "TFBubbleItUp", :path => "../"
end

target 'TFBubbleItUp_Tests' do
  pod "TFBubbleItUp", :path => "../"
end
