source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TFBubbleItUp_Example', :exclusive => true do
  pod "TFBubbleItUp", :path => "../"
end

target 'TFBubbleItUp_Tests', :exclusive => true do
  pod "TFBubbleItUp", :path => "../"

  
end
