name: Test

on:
  - pull_request

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pod lib lint
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec pod lib lint
    - name: Build example app
      run: |
        xcodebuild -project Example/TFBubbleItUp.xcodeproj -scheme Example -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator test
